# Generated by Django 3.0.3 on 2020-02-22 02:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_says', models.CharField(max_length=50)),
                ('cow_said', jsonfield.fields.JSONField()),
            ],
        ),
    ]
