# Generated by Django 3.0.3 on 2020-02-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CowSay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow_model',
            name='cow_said',
        ),
    ]
