# Generated by Django 3.0.3 on 2020-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
