# Generated by Django 3.0.4 on 2020-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField()),
                ('contents', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
            ],
        ),
    ]
